# Generated by Django 5.1.7 on 2025-03-31 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movieupload_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieupload',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='movieupload',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='movieupload',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='movieupload',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
